### ISSUE TITLE
Try to run training on both plausibility datasets to make use of more in-domain samples

### ISSUE THREAD

**Issue by Jacob-Chmura** [Jacob-Chmura/plausibility-vaccine#56]

**Comment by sebastian9991** [comment]
![image](https://github.com/user-attachments/assets/d734b4f3-5f34-419f-821f-57bc368922f7)

Some improvement

**Comment by Jacob-Chmura** [comment]
> ![image](https://private-user-images.githubusercontent.com/61892815/393008409-d734b4f3-5f34-419f-821f-57bc368922f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzY4NjAsIm5iZiI6MTczMzQzNjU2MCwicGF0aCI6Ii82MTg5MjgxNS8zOTMwMDg0MDktZDczNGI0ZjMtNWYzNC00MTlmLTgyMWYtNTdiYzM2ODkyMmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDIyMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDA4NjcxYjFlMTg1ZjZiYzY0ZGQ1Y2VjZWI1YTYzODI5OTFkMWE4OTAwMDJjNGNhOWMyMDEzOTJhZjJkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DZiHXZI6BxiY21IlT-nc-_-sgeTdEx-pKUjFd0FmIX4)
> 
> Some improvement

Very interesting. Interestingly, the MLP base does so poorly. Something is incorrectly set up for that training configuration. Alternatively, the adapters are just superior in low data settings. I'm happy with the improvement from the baseline, though. Makes me think that re-splitting the datasets to like 80-20 instead of (50-50) we would see additional gains.
