### ISSUE TITLE
Statistical Analysis of Association Data

### ISSUE THREAD

**Issue by Jacob-Chmura** [Jacob-Chmura/plausibility-vaccine#67]
Look at correlation between association data an plausibility.

**Comment by Jacob-Chmura** [comment]
@sebastian9991 @jonahdvt I need GPT to provide property / association predictions on the 20q and PEP plausibility datasets, in order to compute relationships between input distributions (property or association) and output distribution (plausibility)

**Comment by sebastian9991** [comment]
I'll work on association predictions.
